### ISSUE TITLE
Working on updating the nf-core/tools template v2.9

### ISSUE THREAD

**Issue by Daniel-VM** [nf-core/bacass#85]
# Issue description

I'm planning to work on updating the nf-core/tools-2.9 (#84 ) template to enhance its functionality, improve documentation, and ensure it aligns with the latest best practices.

To that end I am going through this list: 

- [X] 1. Review the current template codebase.
- [X] 2. Identify deprecated or obsolete components that need to be updated.
- [X] 3. Update dependencies to the latest compatible versions.
- [X] 4. Refactor code to adhere to nf-core coding standards.
- [X] 5. Test the updated template with various data and scenarios.
- [X] 6. Address any issues or bugs found during testing.
- [X] 7. Ensure backward compatibility with existing workflows.
- [X] 8. Linting

I aim to periodically update this issue to provide insights into the progress made. If anyone has expertise in template development or nf-core best practices, your input would be highly appreciated 🙏🏾 .

(edit v3: updated task list)

**Comment by d4straub** [comment]
I already had the thought that it might be easier just to copy code that is relevant to the new template instead of attempting to merge the template...
I assume that most if not all tools have nf-core modules. Andfor example skewer could be exchanged with fastp.
I assume that could be done by cloning the repo, deleting all files, insert fresh template 2.9, install nf-core modeule, copy old code over as far as relevant.
Anyway, just a thought.

**Comment by Daniel-VM** [comment]
Thanks for the input @d4straub. If the merging becomes a headache, then I will try to start from a fresh template 👍🏾

**Comment by Daniel-VM** [comment]
nf-core template v2.9 has been update. Closing issue 👍🏾
